runtime: python311

# Instance configuration
instance_class: F4_1G
automatic_scaling:
  min_instances: 0
  max_instances: 10
  min_idle_instances: 0
  max_idle_instances: 1
  target_cpu_utilization: 0.6

# Environment variables
env_variables:
  GCP_PROJECT_ID: "chitgenie"
  # Add your Gemini API key as an environment variable
  # GEMINI_API_KEY: "your-api-key-here"

# Resource limits
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

# Health check
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# VPC connector (if needed for private resources)
# vpc_access_connector:
#   name: "projects/chitgenie/locations/us-central1/connectors/your-connector"